exec = uwsm-app -- swaybg -i ~/.config/wallpapers/1-pawel-czerwinski.jpg -m fill
exec-once = uwsm-app -- walker --gapplication-service
exec-once = systemctl --user start hyprpolkitagent
exec-once = uwsm-app -- swayosd-server
exec-once = uwsm-app -- waybar
exec-once = uwsm-app -- mako

# Slow app launch fix -- set systemd vars
exec-once = systemctl --user import-environment $(env | cut -d'=' -f 1)
exec-once = dbus-update-activation-environment --systemd --all
