max-gamma = 150

profile {
    time = 6:00
    identity = true  # No filter
}

profile {
    time = 19:00
    temperature = 3500
    gamma = 0.9
}

profile {
    time = 22:00
    temperature = 2700
    gamma = 0.8
}