# Menus
bindd = SUPER, SPACE, Launch apps, exec, walker --width 644 --maxheight 300 --minheight 300
bindd = , XF86Calculator, Calculator, exec, gnome-calculator
bindd = SUPER, R, Screen record menu, exec, ~/.config/hypr/scripts/screenrecord-menu.sh

# Toggles
bindd = SUPER CTRL, I, Toggle locking on idle, exec, ~/.config/hypr/scripts/toggle-idle.sh

# Captures (Something weizZrd with PRINT input, also the VIA config is broken)
bindd = , PRINT, Screenshot, exec, hyprshot -z -m region -o ~/Pictures/Screenshots
bindd = ALT, PRINT, Screenrecording, exec, ~/.config/hypr/scripts/screenrecord-menu.sh
bindd = SUPER, PRINT, Color picker, exec, pkill hyprpicker || hyprpicker -a
bindd = SUPER SHIFT, S, Screenshot, exec, hyprshot -z -m region -o ~/Pictures/Screenshots

# Control panels
bindd = SUPER CTRL, S, Sound controls, exec, uwsm app -- xdg-terminal-exec --app-id=TUI.float wiremix
bindd = SUPER CTRL, A, Activity, exec, uwsm app -- xdg-terminal-exec --app-id=TUI.float btop

# Zoom
bindd = SUPER CTRL, Z, Zoom in, exec, hyprctl keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 1')
bindd = SUPER CTRL ALT, Z, Reset zoom, exec, hyprctl keyword cursor:zoom_factor 1

# Lock system
bindd = SUPER CTRL, L, Lock system, exec, hyprctl switchxkblayout all 0 & (pidof hyprlock || hyprlock &)
